#!/bin/bash
# setup_cluster.sh — multi-node Ray + NCCL setup for verl on RunPod Instant Cluster
#
# Auto-detects RoCE/IB HCAs and high-speed cluster network interfaces, writes
# NCCL env to /root/verl_cluster_env.sh, and starts Ray on this node.
#
# Usage:
#   bash setup_cluster.sh head
#   bash setup_cluster.sh worker <head_internal_ip>
#
# Typical 2-node flow (run from your laptop in two terminals):
#   # Terminal A — SSH into node 0:
#   bash setup_cluster.sh head
#   # script prints HEAD_IP=...
#
#   # Terminal B — SSH into node 1:
#   bash setup_cluster.sh worker <HEAD_IP_from_terminal_A>
#
#   # Back in Terminal A, launch training:
#   source /root/verl_cluster_env.sh
#   NNODES=2 NGPUS_PER_NODE=8 bash <your_train_script>.sh
#
# Env overrides:
#   IFACE_PATTERN   regex of iface names to use   (default: ^(ens|ib)[0-9]+$)
#   IFACE_NET       IP prefix to filter on        (default: 10.)
#   RAY_PORT        ray head port                 (default: 6379)
#   DASHBOARD_PORT  ray dashboard                 (default: 8265)
#   ENV_FILE        where to persist NCCL env     (default: /root/verl_cluster_env.sh)

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

log()  { echo -e "${GREEN}[$(date +%H:%M:%S)]${RESET} $*"; }
warn() { echo -e "${YELLOW}[$(date +%H:%M:%S)] WARN:${RESET} $*"; }
err()  { echo -e "${RED}[$(date +%H:%M:%S)] ERROR:${RESET} $*"; exit 1; }

# ─── Args ───
ROLE="${1:-}"
HEAD_IP="${2:-}"

if [[ "$ROLE" != "head" && "$ROLE" != "worker" ]]; then
    cat <<EOF
Usage: $0 <role> [head_ip]

  role:     head | worker
  head_ip:  required for worker role; the head's IP on the cluster network

Examples:
  bash $0 head                          # on the first node
  bash $0 worker 10.65.0.2              # on every other node
EOF
    exit 1
fi
if [[ "$ROLE" == "worker" && -z "$HEAD_IP" ]]; then
    err "worker role requires head IP as second arg"
fi

# ─── Tunables ───
IFACE_PATTERN="${IFACE_PATTERN:-^(ens|ib)[0-9]+$}"
IFACE_NET="${IFACE_NET:-10.}"
RAY_PORT="${RAY_PORT:-6379}"
DASHBOARD_PORT="${DASHBOARD_PORT:-8265}"
ENV_FILE="${ENV_FILE:-/root/verl_cluster_env.sh}"

# ─── Step 1: discover cluster network interfaces ───
log "Step 1: discovering cluster network ifaces (pattern=$IFACE_PATTERN, net=${IFACE_NET}*)"

mapfile -t IFACES < <(
    ip -4 -o addr show | awk '{print $2, $4}' |
        awk -v pat="$IFACE_PATTERN" -v net="$IFACE_NET" '
            $1 ~ pat && index($2, net) == 1 { print $1 }
        ' | sort -u
)

if [[ ${#IFACES[@]} -eq 0 ]]; then
    err "no cluster ifaces found matching $IFACE_PATTERN with ${IFACE_NET}* IP. \
Override with IFACE_PATTERN and IFACE_NET env vars."
fi

IFACE_LIST=$(IFS=,; echo "${IFACES[*]}")
log "  found ${#IFACES[@]} ifaces: $IFACE_LIST"

# ─── Step 2: pick primary iface for Ray control plane + get own IP ───
PRIMARY_IFACE="${IFACES[0]}"
OWN_IP=$(ip -4 -o addr show "$PRIMARY_IFACE" | awk '{print $4}' | cut -d/ -f1)
[[ -z "$OWN_IP" ]] && err "failed to read IP from $PRIMARY_IFACE"
log "  primary iface (Ray control plane): $PRIMARY_IFACE → $OWN_IP"

# ─── Step 3: discover IB/RoCE HCAs ───
log "Step 3: discovering RDMA HCAs"

if [[ -d /sys/class/infiniband ]]; then
    mapfile -t HCAS < <(ls /sys/class/infiniband/ 2>/dev/null | sort -u)
else
    HCAS=()
fi

if [[ ${#HCAS[@]} -gt 0 ]]; then
    HCA_LIST=$(IFS=,; echo "${HCAS[*]}")
    log "  found ${#HCAS[@]} HCAs: $HCA_LIST"
    # Check port states
    DOWN_HCAS=()
    for hca in "${HCAS[@]}"; do
        state=$(awk '{print $NF}' "/sys/class/infiniband/$hca/ports/1/state" 2>/dev/null || echo "UNKNOWN")
        [[ "$state" != "ACTIVE" ]] && DOWN_HCAS+=("$hca:$state")
    done
    if [[ ${#DOWN_HCAS[@]} -gt 0 ]]; then
        warn "  some HCA ports are not ACTIVE: ${DOWN_HCAS[*]}"
        warn "  NCCL may fall back to TCP for those rails or fail to use them"
    fi
else
    HCA_LIST=""
    warn "  no RDMA HCAs found in /sys/class/infiniband — NCCL will fall back to TCP (slow)"
fi

# ─── Step 4: connectivity check (worker only — verify head is reachable) ───
if [[ "$ROLE" == "worker" ]]; then
    log "Step 4: pinging head $HEAD_IP via $PRIMARY_IFACE"
    if ping -c 2 -W 2 -I "$PRIMARY_IFACE" "$HEAD_IP" >/dev/null 2>&1; then
        log "  head reachable"
    else
        err "head $HEAD_IP not reachable via $PRIMARY_IFACE. \
Check that head_ip is on the cluster network and the head node has run setup_cluster.sh head."
    fi
fi

# ─── Step 5: write NCCL env to a sourceable file ───
log "Step 5: writing NCCL env to $ENV_FILE"

{
    echo "# Generated by verl-deploy/setup_cluster.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
    echo "# source this in any shell that launches verl training on this node."
    echo "export NCCL_SOCKET_IFNAME=$IFACE_LIST"
    echo "export NCCL_NVLS_ENABLE=0"
    if [[ -n "$HCA_LIST" ]]; then
        echo "export NCCL_IB_DISABLE=0"
        echo "export NCCL_IB_HCA=$HCA_LIST"
    fi
    echo "# Uncomment for verbose NCCL debug:"
    echo "# export NCCL_DEBUG=INFO"
    echo "# export NCCL_DEBUG_SUBSYS=INIT,NET"
} > "$ENV_FILE"

log "  contents:"
sed 's/^/    /' "$ENV_FILE"

# shellcheck disable=SC1090
source "$ENV_FILE"

# ─── Step 6: start Ray ───
log "Step 6: starting Ray as $ROLE"

# Stop any prior Ray on this node so re-running is idempotent
if ray status >/dev/null 2>&1; then
    warn "  Ray already running on this node — stopping first"
    ray stop --force >/dev/null 2>&1 || true
    sleep 2
fi

if [[ "$ROLE" == "head" ]]; then
    ray start --head --port="$RAY_PORT" \
        --node-ip-address="$OWN_IP" \
        --dashboard-port="$DASHBOARD_PORT" \
        --dashboard-host=0.0.0.0
else
    ray start --address="$HEAD_IP:$RAY_PORT" \
        --node-ip-address="$OWN_IP"
fi

# ─── Step 7: verify ───
log "Step 7: verifying cluster"
sleep 3
ray status || warn "ray status failed; cluster may still be coming up"

# ─── Final hints ───
echo ""
echo -e "${GREEN}========================================${RESET}"
if [[ "$ROLE" == "head" ]]; then
    echo -e "${GREEN}  Head ready. HEAD_IP for workers:${RESET}"
    echo -e "${GREEN}    $OWN_IP${RESET}"
    echo ""
    echo "  On every worker node, run:"
    echo "    bash $(realpath "$0") worker $OWN_IP"
    echo ""
    echo "  When all workers have joined (ray status shows expected GPU count),"
    echo "  launch training in this shell:"
    echo "    source $ENV_FILE"
    echo "    NNODES=<total_nodes> NGPUS_PER_NODE=8 bash <your_train_script>"
    echo ""
    echo "  Smoke test (16-rank NCCL allreduce on 2 nodes) before training:"
    echo "    python -c 'import ray; ray.init(\"auto\"); print(ray.cluster_resources())'"
else
    echo -e "${GREEN}  Worker joined cluster at $HEAD_IP:$RAY_PORT${RESET}"
    echo "  Nothing else to do on this node — launch training from the head."
fi
echo -e "${GREEN}========================================${RESET}"
